### ISSUE TITLE
@conda-forge-admin please add user @jfolleas1

### ISSUE THREAD

**Issue by PertuyF** [conda-forge/benchling-sdk-feedstock#11]

**Comment by PertuyF** [comment]
Hey @conda-forge/core , @jfolleas1 was added as a maintainer to this feedstock a few months ago, although he's not been added as a member to the organization. This is an issue because then he can't merge the PRs from the bot.

What have we done wrong? Can you help?

**Comment by jakirkham** [comment]
Linking to issue ( https://github.com/conda-forge/conda-forge-webservices/issues/530 ), which is also now reopened, since the comma issue appears to have resurfaced

**Comment by jakirkham** [comment]
@conda-forge-admin, please update team

**Comment by jakirkham** [comment]
Think @jfolleas1 needs to accept their invitation to join the org still. More details in comment ( https://github.com/conda-forge/benchling-sdk-feedstock/commit/babe0ffb255a6115269df062e58bb8291fa539a7#commitcomment-100743237 )

**Comment by PertuyF** [comment]
Thx!
